services :
#    database :
#        image :          postgres
#        container_name : database
#        environment :
#            POSTGRES_USER :     postgres
#            POSTGRES_PASSWORD : root
#            POSTGRES_DB :       publication
#        ports :
#        - 5432:5432
    database :
        image :          mysql
        container_name : database
        environment :
            MYSQL_ROOT_PASSWORD : root
            MYSQL_DATABASE :      publication
        ports :
        - 3306:3306
    application-server :
        image :          application-server:latest
        build :
            context :    back
            dockerfile : Dockerfile
        container_name : application-server
        ports :
        - 8080:8080
        depends_on :
        - database
        environment :
        - SERVER_PORT=8080
        - SPRING_DATASOURCE_URL=jdbc:mysql://database/publication
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    web-server :
        image :          web-server:latest
        build :
            context :    front
            dockerfile : Dockerfile
        container_name : web-server
        ports :
        - 4200:4200
        depends_on :
        - application-server
