spring :
    datasource :

        # PostgreSQL
        url :      jdbc:postgresql://localhost:5432/publication
        #

        # MySQL
#        url :      jdbc:mysql://localhost:3306/publication
        #

        username : postgres
        password : root
    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true

        # for PostgreSQL
        properties :
            hibernate :
                dialect : org.hibernate.dialect.PostgreSQLDialect
                jdbc :
                    lob :
                        non_contextual_creation : true
        #

server :
    port : 8080